"""Render static HTML pages from the shared, editable portfolio content."""
from pathlib import Path
import json, html
ROOT=Path(__file__).resolve().parent
D=json.loads((ROOT/'content/portfolio.json').read_text(encoding='utf-8'))
E=html.escape
def img(file,alt='',lazy=True,cls=''):
    from PIL import Image
    p=ROOT/'assets/img'/file
    w,h=Image.open(p).size
    return f'<img src="assets/img/{file}" alt="{E(alt)}" width="{w}" height="{h}" class="{cls}" loading="{"lazy" if lazy else "eager"}" decoding="async">'
def screenfile(group,name):return f'{group}/{name}.'+('png' if group=='repup' and name=='home' else 'webp')
def zoom(file,label):return f'<button type="button" data-zoom="assets/img/{file}" data-caption="{E(label)}" aria-label="Enlarge {E(label)}">{img(file,label)}</button>'
def figure(file,label):return f'<figure class="figure">{zoom(file,label)}<figcaption>{E(label)} · Select to enlarge</figcaption></figure>'
def phones(group,names):return '<div class="phone-cluster">'+''.join(img(screenfile(group,n),f'{group.title()} {n.replace("-"," ")}',False) for n in names)+'</div>'
def artwork(slug):
    if slug=='repup':
        return '<div class="card-art repup-art"><div class="art-heading"><span class="visual-brand">RepUp</span><span class="art-category">A clearer way<br>to get moving.</span></div><div class="mockup-set repup-set">'+''.join(img('mockups/repup-'+n+'.png','RepUp '+n+' in the original device mockup',False,cls='mockup mockup-'+n) for n in ['insights','home','workout'])+'</div><span class="art-label">01 / PRODUCT DESIGN</span></div>'
    if slug=='meridian':
        return '<div class="card-art meridian-art"><div class="art-heading"><span class="visual-brand">Meridian</span><span class="art-category">Journeys,<br>drawn by hand.</span></div>'+img('mockups/meridian-home.png','Original Meridian MacBook mockup showing the travel homepage',False,cls='laptop-mockup')+'<span class="art-label">02 / WEB DESIGN</span></div>'
    if slug=='zomato':
        return '<div class="card-art zomato-art"><div class="art-heading"><span class="visual-brand">zomato</span><span class="art-category">Information<br>architecture.</span></div><div class="intent-statement">Intent.<br><span>Then action.</span></div><div class="intent-toggle"><span>Order in</span><span>Dine out</span></div><div class="mini-ia"><span>Home</span><span>Search</span><span>Orders</span><span>Account</span></div><span class="art-label">03 / UX STRATEGY</span></div>'
    return '<div class="card-art verge-art"><div class="art-heading"><span class="visual-brand">Verge</span><span class="art-category">A little space<br>to think clearly.</span></div><div class="mockup-set verge-set">'+img('mockups/verge-start.png','Original Verge mockup: name the decision',False,cls='mockup')+img('mockups/verge-review.png','Original Verge mockup: reflect on readiness',False,cls='mockup')+'</div><span class="art-label">04 / INTERACTION DESIGN</span></div>'

def nav(active):
    links=''.join(f'<a href="{url}"'+(' aria-current="page"' if active==label else '')+f'>{label}</a>' for label,url in [('Work','index.html#work'),('Explorations','explorations.html'),('About','about.html')])
    return '<a class="skip" href="#main">Skip to content</a><header class="header"><div class="wrap nav"><a class="brand" href="index.html" aria-label="Abhijith U home"><span class="brand-mark" aria-hidden="true">a.</span>Abhijith U</a><nav class="nav-links" aria-label="Main navigation">'+links+'<a class="nav-contact" href="mailto:'+D['email']+'">Let’s talk ↗</a></nav></div></header>'
def footer():return f'''<footer class="footer"><div class="wrap"><div class="footer-top"><span>Have something in mind?</span><span>OPEN TO UI/UX & UI DEVELOPER ROLES</span></div><a class="footer-title" href="mailto:{D['email']}">Let’s talk<span aria-hidden="true">↗</span></a><div class="footer-main"><a class="footer-contact" href="mailto:{D['email']}">{D['email']}</a><div class="footer-links"><a href="https://www.behance.net/abhijithuvishnu" target="_blank" rel="noreferrer">Behance ↗</a><a href="https://github.com/Abhijith2198" target="_blank" rel="noreferrer">GitHub ↗</a><a href="assets/Abhijith-U-Resume.pdf" download>Resume ↓</a></div></div><div class="footer-base"><span>© 2026 Abhijith U</span><span>Thiruvananthapuram, India</span><a href="#main">Back to top ↑</a></div></div></footer>'''

def page(title,description,body,file,active='Work'):
    canonical='https://abhijith2198.github.io/'+('' if file=='index.html' else file)
    doc=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{E(title)} — Abhijith U</title><meta name="description" content="{E(description)}"><meta name="theme-color" content="#ffffff"><link rel="canonical" href="{canonical}"><meta property="og:title" content="{E(title)} — Abhijith U"><meta property="og:description" content="{E(description)}"><meta property="og:type" content="website"><meta property="og:url" content="{canonical}"><link rel="icon" href="assets/img/favicon.svg" type="image/svg+xml"><link rel="preload" href="assets/fonts/archivo-latin-wdth-normal.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="assets/css/portfolio.css"><link rel="stylesheet" href="assets/css/showcase.css"><script src="assets/js/portfolio.js" defer></script></head><body class="page-{file.removesuffix('.html')}">{nav(active)}<main id="main">{body}</main>{footer()}<dialog class="lightbox" id="image-viewer" aria-label="Enlarged project image"><button type="button" aria-label="Close enlarged image">Close ×</button><img alt=""><p></p></dialog></body></html>'''
    (ROOT/file).write_text(doc,encoding='utf-8')
def cards():
    out=''
    for p in D['projects']:
        out+=f'''<article id="project-{p['slug']}" class="project-card feature-{p['slug']}"><a href="{p['slug']}.html" aria-label="Read {E(p['name'])} case study">{artwork(p['slug'])}<div class="card-meta"><div><div class="eyebrow">{p['number']} / {p['category']}</div><h3>{p['name']}</h3><p>{p['summary']}</p></div><span class="circle-link" aria-hidden="true">↗</span></div></a></article>'''
    return out
def fieldnotes():
    return '<section class="field-notes wrap"><div class="notes-heading"><p class="eyebrow">FIELD NOTES</p><h2>Behind the work.</h2><a class="text-link" href="explorations.html">More explorations ↗</a></div><div class="notes-list">'+''.join(f'<article><span class="note-number">({n["number"]})</span><div><p class="eyebrow">{n["tag"]}</p><h3>{n["title"]}</h3><p>{n["text"]}</p><a class="text-link" href="{n["link"]}">{n["linkLabel"]} ↗</a></div></article>' for n in D['fieldNotes'])+'</div></section>'
def workindex():return '<nav class="work-index" aria-label="Project index">'+''.join(f'<a href="#project-{p["slug"]}"><span>{p["name"]}</span><span>{p["number"]}</span></a>' for p in D['projects'])+'</nav>'
home=f'''<section class="showcase-hero" style="background-image:url('assets/img/{E(D['coverBackground'])}')" aria-labelledby="portfolio-title"><div class="hero-topline"><p>Selected design work<br><strong>Abhijith U</strong><small>Product design / Web design</small></p><span class="identity-seal" role="img" aria-label="Abhijith U, UI/UX designer. Think, make, build."><svg viewBox="0 0 120 120" aria-hidden="true" focusable="false"><defs><path id="seal-top-arc" d="M16 60 A44 44 0 0 1 104 60"/><path id="seal-bottom-arc" d="M16 60 A44 44 0 0 0 104 60"/></defs><circle cx="60" cy="60" r="58" fill="none" stroke="currentColor" stroke-width=".8"/><g fill="currentColor" font-family="Archivo, Arial, sans-serif" font-weight="600"><text font-size="10.5" letter-spacing=".15"><textPath href="#seal-top-arc" startOffset="50%" text-anchor="middle">UI / UX DESIGN</textPath></text><text x="59" y="72" font-size="38" letter-spacing="-2" text-anchor="middle">au.</text><text font-size="10.5" letter-spacing=".15"><textPath href="#seal-bottom-arc" startOffset="50%" text-anchor="middle">THINK / MAKE / BUILD</textPath></text></g></svg></span></div><div class="hero-objects" aria-hidden="true"><svg class="hero-plinth" viewBox="0 0 1200 60" preserveAspectRatio="none" focusable="false"><path d="M55 0H1145L1200 38H0Z" fill="#f6f5ef"/><path d="M0 38H1200V60H0Z" fill="#d1d0c7"/><path d="M0 38H1200" fill="none" stroke="#fff" stroke-width="1.5"/></svg>{img('mockups/meridian-home.png','',False,cls='hero-laptop')}{img('mockups/verge-review.png','',False,cls='hero-phone hero-verge')}</div><div class="hero-type"><h1 id="portfolio-title">Portfolio</h1></div><div class="hero-bottomline"><a href="#work">Explore selected work ↓</a><span>THIRUVANANTHAPURAM, INDIA</span><a href="assets/Abhijith-U-Portfolio.pdf" download>Portfolio PDF ↗</a></div></section><section class="hello wrap"><div class="hello-mark" aria-hidden="true">au.</div><h2>Hello!<br>I’m Abhijith.</h2><p>{D['bio']}</p><div class="skill-pills"><span>UI/UX design</span><span>Web design</span><span>Information architecture</span><span>Interaction design</span><span>HTML & CSS</span></div><a class="text-link" href="about.html">From engineering to design ↗</a></section><section class="wrap work-section" id="work"><div class="work-heading"><h2>Selected<br>work<span>.</span></h2>{workindex()}</div><div class="project-grid">{cards()}</div></section><section class="editorial-pause"><div class="wrap"><p class="eyebrow">A THREAD THROUGH THE WORK</p><p class="pause-statement">Clarity is a<br>design decision.</p><div class="pause-foot"><span aria-hidden="true">↳</span><p>What to bring forward. What to leave out. And how to make the next step feel clear.</p></div></div></section>{fieldnotes()}'''
page('UI/UX designer',D['bio'],home,'index.html')
def facts(p):return '<dl class="case-facts">'+''.join(f'<div><dt>{label}</dt><dd>{E(p[key])}</dd></div>' for label,key in [('Role','role'),('Timeline','timeline'),('Platform / scope','platform'),('Tools','tools')])+'</dl>'
def section(n,label,content):return f'<section id="{label.lower().replace(" ","-")}"><div class="section-title"><span class="eyebrow">0{n}</span><h2>{label}</h2></div>{content}</section>'
def steps(p):return '<div class="steps">'+''.join(f'<div class="step"><p class="num">0{i+1}</p><h3>{E(s["title"])}</h3><p>{E(s["text"])}</p></div>' for i,s in enumerate(p['process']))+'</div>'
def screens(group,names):return '<div class="screens">'+''.join(f'<figure class="screen">{zoom(screenfile(group,n),group.title()+" · "+n.replace("-"," ").title())}<figcaption>{n.replace("-"," ").title()}</figcaption></figure>' for n in names)+'</div>'
def ia(p):return '<div class="ia-tree"><div class="ia-root">Zomato</div><div class="ia-columns">'+''.join('<div class="ia-column"><h3>'+t['title']+'</h3><ul>'+''.join('<li>'+i+'</li>' for i in t['items'])+'</ul></div>' for t in p['tabs'])+'</div><p class="deep-links">Blinkit & District · Reachable as deep links outside the core tabs</p></div>'
for idx,p in enumerate(D['projects']):
    slug=p['slug']
    header=f'<div class="wrap case-header"><a class="back" href="index.html#work">← All selected work</a><div class="case-heading"><div><p class="eyebrow">{p["number"]} / {p["category"]}</p><h1>{p["name"]}</h1></div><div><p class="summary">{p["tagline"]}</p><p class="case-status">{p["status"]}</p></div></div>{facts(p)}</div><div class="wrap case-hero">{artwork(slug)}</div>'
    body=section(1,'Overview',f'<p class="lead">{p["overview"]}</p><p><a class="text-link" href="{p["figma"]}" target="_blank" rel="noreferrer">Explore the Figma file ↗</a></p>')
    body=body.replace('<p class="lead">',f'<div class="case-editorial"><p class="eyebrow">THE DESIGN INTENT</p><h3 class="intent-heading">{p["editorial"]["title"]}</h3><p>{p["editorial"]["text"]}</p></div><p class="lead">',1)
    problem=f'<h3>{p["problemTitle"]}</h3><p class="lead">{p["problem"]}</p>'
    if slug=='repup':problem+='<div class="metrics">'+''.join(f'<div class="metric"><strong>{r["value"]}</strong><span>{r["label"]}</span></div>' for r in p['research'])+f'</div><p class="note">{p["researchNote"]}</p><blockquote class="quote">“{p["quote"]}”<cite>REPUP · INTERVIEW PARTICIPANT</cite></blockquote>'
    body+=section(2,'Problem',problem)
    process=steps(p)
    if slug=='repup':process+=figure('repup/board-ia.webp','Six sections establish the product structure')+figure('repup/board-lofi.webp','Core wireframes establish hierarchy before visual styling')
    elif slug=='meridian':process+=figure('meridian/home-routes.webp','Signature routes after mentor feedback')
    body+=section(3,'Process',process)
    decisions=''
    for i,s in enumerate(p['decisions']):
        media=f'<div class="decision-media {"phone" if slug=="repup" else ""}">{zoom(s["image"],s["title"])}</div>' if 'image' in s else ''
        decisions+=f'<article class="decision"'+(' style="grid-template-columns:1fr"' if not media else '')+f'><div><p class="decision-index">DECISION / 0{i+1}</p><h3>{s["title"]}</h3><p>{s["text"]}</p></div>{media}</article>'
    if slug=='zomato':decisions+=ia(p)
    body+=section(4,'Key decisions',decisions)
    if slug=='repup':
        final='<p>23 screens form the current visual design. Select a screen to inspect it at a larger size.</p>'+screens('repup',['home','workout','insights'])+'<details class="gallery-details"><summary>Explore all 23 screens</summary>'
        for g in p['screenGroups']:final+=f'<div class="screen-group"><h3>{g["name"]}</h3>{screens("repup",g["files"])}</div>'
        final+='</details><p class="note">Visual system: Poppins · Iconify · 4 px spacing scale · Navy, primary green and lime.</p>'
    elif slug=='meridian':final=figure('meridian/home-hero.webp','Desktop homepage · inquiry and route motif')+figure('meridian/journal.webp','Journal index · an editorial extension of the brand')+figure('meridian/article.webp','Article page · long-form reading')+screens('meridian',['mobile-hero','mobile-collection','mobile-how'])+'<p class="note">Travel photography is used within this fictional design concept.</p>'
    elif slug=='verge':final=screens('verge',['step-1','step-2','step-3','step-4'])
    else:
        final='<p class="lead">The final artifact is a clearer structure and an ordering flow.</p><div class="flow-grid">'+''.join(f'<div class="flow-item"><span>0{i+1}</span>{f}</div>' for i,f in enumerate(p['flow']))+'</div><table class="comparison"><thead><tr><th scope="col">Audited structure</th><th scope="col">Proposed structure</th></tr></thead><tbody><tr><td>Verticals compete for navigation</td><td>Four fixed, task-based tabs</td></tr><tr><td>12+ cuisine shortcuts at once</td><td>Six initial options with See all</td></tr><tr><td>Mixed delivery and dining content</td><td>Order in / Dine out intent first</td></tr><tr><td>Grocery and events in the core navigation</td><td>Separate, clearly signposted deep links</td></tr></tbody></table>'
    body+=section(5,'Final screens' if slug!='zomato' else 'Final structure',final)
    body+=f'<section id="next"><div class="next-box"><p class="eyebrow">06 / WHAT I’D DO NEXT</p><h2 style="margin-top:20px">The next useful question.</h2><p class="lead">{p["next"]}</p></div></section>'
    labels=[('overview','Overview'),('problem','Problem'),('process','Process'),('key-decisions','Key decisions'),('final-structure' if slug=='zomato' else 'final-screens','Final structure' if slug=='zomato' else 'Final screens'),('next','What’s next')]
    subnav='<aside class="case-nav" aria-label="Case study sections">'+''.join(f'<a href="#{a}"><span>0{i+1}</span>{b}</a>' for i,(a,b) in enumerate(labels))+'</aside>'
    nxt=D['projects'][(idx+1)%4]
    out=header+f'<div class="wrap case-shell">{subnav}<div class="case-body">{body}</div></div>'+f'<a class="next-project" href="{nxt["slug"]}.html"><div><p class="eyebrow">NEXT CASE STUDY / {nxt["number"]}</p><h2>{nxt["name"]}</h2></div><span style="font-size:65px" aria-hidden="true">↗</span></a>'
    page(p['name'],p['summary'],out,slug+'.html',active='')
about='<div class="wrap"><section class="about-hero"><p class="eyebrow">ABOUT / THE PERSON BEHIND THE WORK</p><h1>Curious about systems.<br><span class="serif">Committed to people.</span></h1></section><section class="about-intro"><div class="about-monogram"><p class="eyebrow">ABHIJITH U / UI/UX DESIGNER</p><strong>au.</strong><p class="eyebrow">ENGINEERING → ROBOTICS → DESIGN</p></div><div class="about-copy"><p class="lead">'+D['bio']+'</p>'+''.join('<p>'+p+'</p>' for p in D['about'])+'<div class="actions"><a class="button solid" href="assets/Abhijith-U-Resume.pdf" download>Download resume ↓</a><a class="text-link" href="mailto:'+D['email']+'">Get in touch ↗</a></div></div></section><section class="credentials">'
for title,key in [('Experience','experience'),('Education','education')]:about+='<div><h2>'+title+'</h2>'+''.join('<article class="credential"><h3>'+x['title']+'</h3><p>'+x['detail']+'</p></article>' for x in D[key])+'</div>'
about+='</section><div class="tools-band"><p class="eyebrow">THINK / MAKE / BUILD</p><p>Figma · Adobe Illustrator · Blender<br>HTML · CSS · Python</p></div></div>'
page('About',D['bio'],about,'about.html','About')
explore='<div class="wrap"><section class="about-hero"><p class="eyebrow">EXPLORATIONS / A CLOSER LOOK</p><h1>Small details.<br><span class="serif">Deliberate choices.</span></h1><p class="lead" style="margin-top:30px">Selected studies in motion, visual systems and interaction, drawn from the projects in this portfolio.</p></section><div class="explore-grid">'
items=[('The route as a signature','meridian/home-route.webp','A mask and Smart Animate reveal a route across the hero. Waypoints and coordinates turn a decorative detail into a repeatable brand idea.','meridian','Motion study · Meridian'),('Progress, made visible','repup/insights.webp','A closer look at the fitness dashboard: lime accents bring attention to progress, while the dark surface separates data from action.','repup','Visual system · RepUp'),('The language of uncertainty','verge/step-4.webp','A readiness slider and the option to say Not yet explore how an interface can leave room for uncertainty.','verge','Interaction study · Verge')]
for title,file,desc,slug,tag in items:explore+=f'<article class="explore-card"><div class="explore-visual {"dark" if slug=="repup" else ""}">{zoom(file,title)}</div><p class="eyebrow" style="margin-top:22px">{tag}</p><h2>{title}</h2><p>{desc}</p><a class="text-link" href="{slug}.html">See the full project ↗</a></article>'
explore+='</div></div>'
page('Explorations','Studies in motion, visual systems and interaction by Abhijith U.',explore,'explorations.html','Explorations')
(ROOT/'.nojekyll').write_text('')
(ROOT/'assets/img/favicon.svg').write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="32" fill="#4778E8"/><text x="12" y="46" font-family="Arial,sans-serif" font-size="47" font-weight="bold" fill="#FFFFFF">a.</text></svg>')
print('Rendered seven HTML pages from shared content.')
